### ISSUE TITLE
Jobs executed with errors in organization with empty fields

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#217]
Steps:
1. Set up zebrunner ce from develop branch
2. switch manually ZEBRUNNER_VERSION=develop for global env
3. switch pipeline version from master to develop for RegisterOrganization and RegisterRepository jobs in Management_Jobs
4. try to registerOrganization with empty repo url and/or token and scan repo
Actual result: Web demo job executed with errors
Expected: Web demo job executed without errors but results not published to reporting

[ERROR] hudson.AbortException: not able to provide the file [ManagedFile: id=agent.env, targetLocation=null, variable=agent], can't be resolved by any provider - maybe it got deleted by an administrator?
	at org.jenkinsci.lib.configprovider.model.ConfigFileManager.provisionConfigFile(ConfigFileManager.java:72)
	at org.jenkinsci.plugins.configfiles.buildwrapper.ManagedFileUtil.provisionConfigFiles(ManagedFileUtil.java:82)
	at org.jenkinsci.plugins.configfiles.buildwrapper.ConfigFileBuildWrapper.setUp(ConfigFileBuildWrapper.java:61)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:117)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[Pipeline] findFiles
[Pipeline] }
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.NullPointerException: Cannot invoke method getTestRunByCiRunId() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.zebrunner.jenkins.pipeline.runner.maven.TestNG.runJob(TestNG.groovy:439)
	at ___cps.transform___(Native Method)

**Comment by vdelendik** [comment]
fixed. we should allow to register valid url and/or token.
at the same time for such cases we put into the log error message:
```
00:12:06  [ERROR] Unable to register valid reporting integration! Required field 'reportingServiceUrl' is missing!
and/or
00:12:06  [ERROR] Unable to register valid reporting integration! Required field 'reportingAccessToken' is missing!
```
and generate agent.env config file with disabled reporting by default:
```
REPORTING_ENABLED=false
REPORTING_SERVER_HOSTNAME=http://52.7.165.168
REPORTING_SERVER_ACCESS_TOKEN=
```

that's doesn't block CI/CD and we could ru web/api jobs and see results in jenkins but wihtout integration with reporting!
