### ISSUE TITLE
RegisterOrganization doesn't work 

### ISSUE THREAD

**Issue by dhreben** [zebrunner/pipeline-ce#28]
Test scenario:

1.Open Jenkins
2.Tap Management_Jobs
3.Tap RegisterOrganization
4.Run build

Actual result:RegisterOrganization doesn't work.

```
18:39:46  [INFO] GitHub->clone
18:39:46  GIT_URL: https://github.com/zebrunner/pipeline-ce.git
18:39:46  branch: {must_override}
[Pipeline] checkout
18:39:46  Selected Git installation does not exist. Using Default
18:39:46  The recommended git tool is: NONE
18:39:46  No credentials specified
18:39:46  Cloning the remote Git repository
18:39:46  Cloning repository https://github.com/zebrunner/pipeline-ce.git
18:39:46   > git init /var/jenkins_home/jobs/Management_Jobs/jobs/RegisterOrganization/workspace/pipeline-ce # timeout=10
18:39:46  Fetching upstream changes from https://github.com/zebrunner/pipeline-ce.git
18:39:46   > git --version # timeout=10
18:39:46   > git --version # 'git version 2.20.1'
18:39:46   > git fetch --tags --force --progress -- https://github.com/zebrunner/pipeline-ce.git +refs/heads/*:refs/remotes/origin/* # timeout=10
18:39:46   > git config remote.origin.url https://github.com/zebrunner/pipeline-ce.git # timeout=10
18:39:46   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
18:39:46  Avoid second fetch
18:39:46   > git rev-parse origin/{must_override}^{commit} # timeout=10
18:39:46   > git rev-parse {must_override}^{commit} # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE


```

**Comment by vdelendik** [comment]
it should be fixed in zebrunner/zebrunner (branch: develop)

**Comment by dhreben** [comment]
fixed

**Comment by dhreben** [comment]
Test scenario:

1.Git clone from develop
2.Open Jenkins
3.Tap Management_Jobs
4.Tap RegisterOrganization
5.Run build

Actual result:RegisterOrganization doesn't work.

```
Started by user admin
Resume disabled by user, switching to high-performance, low-durability mode.
Loading library Zebrunner-CE@develop
Attempting to resolve develop from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
 > git ls-remote -h -- https://github.com/zebrunner/pipeline-ce.git # timeout=10
Found match: refs/heads/develop revision 9b4538796e6c3e630c6bd269f9d40d18afa3f36b
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/zebrunner/pipeline-ce.git
 > git init /var/jenkins_home/jobs/Management_Jobs/jobs/RegisterOrganization/workspace@libs/Zebrunner-CE # timeout=10
Fetching upstream changes from https://github.com/zebrunner/pipeline-ce.git
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
 > git fetch --no-tags --force --progress -- https://github.com/zebrunner/pipeline-ce.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/zebrunner/pipeline-ce.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision 9b4538796e6c3e630c6bd269f9d40d18afa3f36b (develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9b4538796e6c3e630c6bd269f9d40d18afa3f36b # timeout=10
Commit message: "Merge pull request #36 from zebrunner/#8"
[Pipeline] Start of Pipeline
[Pipeline] echo
VARS:
[Pipeline] echo
CORE_LOG_LEVEL=INFO
[Pipeline] echo
JACOCO_BUCKET=jacoco.qaprosoft.com
[Pipeline] echo
JACOCO_REGION=us-west-1
[Pipeline] echo
JACOCO_ENABLE=false
[Pipeline] echo
JOB_MAX_RUN_TIME=60
[Pipeline] echo
ZEBRUNNER_VERSION=develop
[Pipeline] echo
ZEBRUNNER_PIPELINE=https://github.com/zebrunner/pipeline-ce.git
[Pipeline] echo
ADMIN_EMAILS=qps-auto@qaprosoft.com
[Pipeline] echo
GIT_TYPE=github
[Pipeline] echo
INFRA_HOST=54.204.162.187
[Pipeline] echo
SELENIUM_URL=********
[Pipeline] echo
capabilities.provider=selenium
[Pipeline] echo
REPORTING_ACCESS_TOKEN=********
[Pipeline] echo
REPORTING_SERVICE_URL={must_override}
[Pipeline] echo
JOB_URL=http://54.204.162.187:80/jenkins/job/Management_Jobs/job/RegisterOrganization/
[Pipeline] echo
JOB_NAME=Management_Jobs/RegisterOrganization
[Pipeline] echo
JOB_BASE_NAME=RegisterOrganization
[Pipeline] echo
BUILD_NUMBER=1
[Pipeline] echo
screen_record_ftp=ftp://${INFRA_HOST}/%s.mp4
[Pipeline] echo
screen_record_host=http://${INFRA_HOST}/video/%s
[Pipeline] echo
screen_record_user=qpsdemo
[Pipeline] echo
screen_record_pass=qpsdemo
[Pipeline] echo
screen_record_duration=1800
[Pipeline] echo
s3_save_screenshots=true
[Pipeline] echo
vnc_desktop=%s://%s:%s/vnc/%s
[Pipeline] echo
vnc_mobile=%s://%s:%s/websockify
[Pipeline] echo
vnc_protocol=ws
[Pipeline] echo
vnc_host=${INFRA_HOST}
[Pipeline] echo
vnc_port=80
[Pipeline] echo
capabilities.enableVNC=true
[Pipeline] echo
capabilities.enableVideo=true
[Pipeline] echo
capabilities.STF_ENABLED=false
[Pipeline] echo
user.timezone=UTC
[Pipeline] echo
s3_local_storage=/opt/apk
[Pipeline] echo
appcenter_local_storage=/opt/apk
[Pipeline] echo
BROWSERSTACK_ACCESS_KEY=********
[Pipeline] echo
TESTRAIL_SERVICE_URL=
[Pipeline] echo
TESTRAIL_USERNAME=
[Pipeline] echo
TESTRAIL_PASSWORD=********
[Pipeline] echo
QTEST_SERVICE_URL=
[Pipeline] echo
QTEST_ACCESS_TOKEN=********
[Pipeline] echo
DOCKER_HUB_USERNAME={must_override}
[Pipeline] echo
DOCKER_HUB_PASSWORD={must_override}
[Pipeline] echo
PARAMS:
[Pipeline] echo
folderName=dhreben
[Pipeline] echo
reportingServiceUrl=http://54.204.162.187
[Pipeline] echo
reportingAccessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiJ3Y2VGenpzRHUyRlRjK01yL0N6QlBwWmhWVC85TU9kbiIsImV4cCI6Mzc1MDkyOTcyM30.m_2xpDnAo2MyF4zUvLZC-SDuhGHIRYXtn8Q9INJ-eXN96yW9Nw1_MsIeUjr3Q69NlkjqNI7rf3RjpyKeDcdl7Q
[Pipeline] echo
customPipeline=false
[Pipeline] echo
callbackUrl=
[Pipeline] echo
accessToken=
[Pipeline] echo
securityEnabled=false
[Pipeline] echo
jobName: Management_Jobs/RegisterOrganization
[Pipeline] echo
nameCount: 2
[Pipeline] echo
orgFolderName: 
[Pipeline] End of Pipeline
java.lang.NullPointerException: Cannot invoke method split() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zebrunner.jenkins.BaseObject.initRepo(BaseObject.groovy:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.zebrunner.jenkins.BaseObject.<init>(BaseObject.groovy:53)
	at com.zebrunner.jenkins.pipeline.Organization.<init>(Organization.groovy:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:208)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onNewInstance(GroovyInterceptor.java:42)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onNewInstance(SandboxInterceptor.java:172)
	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:205)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedConstructor(Checker.java:210)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.constructorCall(SandboxInvoker.java:21)
	at WorkflowScript.run(WorkflowScript:3)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE

```

**Comment by vdelendik** [comment]
fixed

**Comment by dhreben** [comment]
Fixed
