### ISSUE TITLE
onPush job is failed during register repo with [ERROR] groovy.lang.MissingMethodException

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#286]
`16:01:47  [ERROR] groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.BuildParametersContext.concurrentBuild() is applicable for argument types: (java.lang.Boolean) values: [true]
16:01:47  	at jdk.internal.reflect.GeneratedConstructorAccessor197.newInstance(Unknown Source)
16:01:47  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:01:47  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
16:01:47  	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
16:01:47  	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
16:01:47  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:266)
16:01:47  	at javaposse.jobdsl.dsl.AbstractExtensibleContext.methodMissing(AbstractExtensibleContext.groovy:19)
16:01:47  	at jdk.internal.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
16:01:47  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:01:47  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:01:47  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
16:01:47  	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:951)
16:01:47  	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1279)
16:01:47  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1227)
16:01:47  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
16:01:47  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
16:01:47  	at javaposse.jobdsl.dsl.AbstractContext.invokeMethod(AbstractContext.groovy)
16:01:47  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
16:01:47  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:340)`

**Comment by okamara** [comment]
this error is not present, will add a new bug with new error
