### ISSUE TITLE
SmartJobsRerun doesn't work

### ISSUE THREAD

**Issue by dhreben** [zebrunner/pipeline-ce#33]
Test scenario:

1.Open Jenkins
2.Tap Management_Jobs
3.Tap SmartJobsRerun
4.Run build

Actual result: SmartJobsRerun doesn't work

```
[DEBUG] tokenName: reporting_service_url; tokenValue: 
[Pipeline] echo
[DEBUG] tokenName: reporting_access_token; tokenValue: 
[Pipeline] echo
[DEBUG] zafira is not connected!
[Pipeline] echo
[DEBUG] refreshToken: ; serviceURL: ;
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
java.lang.NullPointerException: Cannot invoke method size() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.zebrunner.jenkins.pipeline.integration.zafira.ZafiraUpdater.smartRerun(ZafiraUpdater.groovy:42)
	at com.zebrunner.jenkins.pipeline.runner.maven.TestNG.rerunJobs(TestNG.groovy:1434)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
	at jdk.internal.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE

```

**Comment by vdelendik** [comment]
fixed. the root cause of the issue - missed foderName parameter wher we have to provide tenant/org name.

test scenario:
1. register repo inside the new org
2. run api_regression cron job
3. mark any test as failed
4. detect valid id of the upstream job id (api_regression) in postgres db
```
docker exec -ti postgres bash
root@cfeed40507ca:/# psql -U postgres
psql (9.6.6)
Type "help" for help.

postgres=# select * from zafira.jobs;
 id | user_id |         name          |                                     job_url                                      |          jenkins_host          | automation_server_id |        modified_at         |         created_at
----+---------+-----------------------+----------------------------------------------------------------------------------+--------------------------------+----------------------+----------------------------+----------------------------
  1 |         | launcher              | http://52.7.165.168:80/jenkins/job/launcher                                      | http://52.7.165.168:80/jenkins |                      | 2020-11-21 16:37:36.991746 | 2020-11-21 16:37:36.991746
  2 |       1 | Tags-Demo-Test        | http://52.7.165.168:80/jenkins/job/qps/job/carina-demo/job/Tags-Demo-Test        | http://52.7.165.168:80/jenkins |                   11 | 2020-11-21 16:49:30.793338 | 2020-11-21 16:49:30.793338
  3 |       1 | API-Demo-Test         | http://52.7.165.168:80/jenkins/job/qps/job/carina-demo/job/API-Demo-Test         | http://52.7.165.168:80/jenkins |                   11 | 2020-11-21 16:49:30.806551 | 2020-11-21 16:49:30.806551
  **4** |       1 | **api_regression**        | http://52.7.165.168:80/jenkins/job/qps/job/carina-demo/job/api_regression        | http://52.7.165.168:80/jenkins |                   11 | 2020-11-21 16:49:30.882676 | 2020-11-21 16:49:30.882676
  6 |       1 | API-CustomParams-Demo | http://52.7.165.168:80/jenkins/job/qps/job/carina-demo/job/API-CustomParams-Demo | http://52.7.165.168:80/jenkins |                   11 | 2020-11-21 16:49:31.305243 | 2020-11-21 16:49:31.305243
(5 rows)
```
Note: in my case it is 4

5. run Management/SmartJobsRerun job providing as arguments
folderName: your actual org/tenant name
upstreamJobId: 4 (see step 4 above^^^)
upstreamJobBuildNumber: 1 (if it was first api_regression run)
doRebuild: false
rerunFailures: true
-> in console logs you should see number of jobs for this cron with failure
`[INFO] Results : 1`
6. Repeit step 5 with doRebuild=true and rerunFailures=true
-> job with failure is restarted. Among job params "rerun_failures is true"
![image](https://user-images.githubusercontent.com/4551455/99883143-8075ec00-2c36-11eb-8e63-03dd7fdfa2c9.png)
-> only failed tests are re-executed and re-registered


repait steps 1-6 for the empty org name

**Comment by okamara** [comment]
I still repro this issue
<img width="963" alt="Screen Shot 2020-11-23 at 8 54 33 PM" src="https://user-images.githubusercontent.com/32964663/99997567-666f1180-2dce-11eb-93fc-b993638cfb54.png">

**Comment by okamara** [comment]
Re-verified. Fixed.
