### ISSUE TITLE
be able to override mavenSettingsConfig without private custom pipeline usage

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#54]
in mavenBuilds.groovy default call has empty mavenSettingsConfig param
```
def call(goals = '-U clean compile test', mavenSettingsConfig = '', mavenLocalRepo = '')
```

I think it might be useful to register new global var like MAVEN_SETTINGS_CONFIG_ID and if param empty but global var not - use this custom settings.xml.
That's allow to support custom settings.xml without developing private pipeline

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/pull/77

as a test scenario:
1. clone from scratch using zebrunner develop branch
-> double check that jenkins/.env for jenkins-master has 1.3-beta3 (!)
2. register org and repo, enable ZEBRUNNER_LOG_LEVEL=DEBUG, run api job
-> analyze console logs to see that empty custom settings are used for maven
```
15:28:22  [DEBUG] MavenSettings: qps-maven; name: ; id: 
[Pipeline] echo
15:28:22  [INFO] mavenBuild->call
[Pipeline] echo
15:28:22  [DEBUG] mavenSettingsConfig: 
```
3. generate new custom maven settings xml using Management_Jobs/RegisterMavenSettings job
Manage Jenkins -> Managed files -> Add a new Config -> Maven settings.xml
**Remember ID**
Submit -> paste customized maven settings -> Submit
Run RegisterMavenSettings and register above ID for your organization (folderName)
Note: default value for xml file is fine

4. again run your api test job 
-> analyze console logs to see that custom maven settings are used
```
15:28:45  [DEBUG] MavenSettings: qps-maven; name: MySettings; id: 558afdb9-3bc1-405e-af38-9c4a370236cc
[Pipeline] echo
15:28:45  [INFO] mavenBuild->call
[Pipeline] echo
15:28:45  [DEBUG] mavenSettingsConfig: 558afdb9-3bc1-405e-af38-9c4a370236cc
```

**Comment by dhreben** [comment]
Test scenario:
1.Clone from scratch using zebrunner develop branch
2.nano jenkins/.env
3.Check that TAG_JENKINS_MASTER=1.3-beta3
4.Run RegisterOrganization
5.Run RegisterRepository
6.Enable ZEBRUNNER_LOG_LEVEL=DEBUG
7.Run API-Demo-Test
8.Tap Console output  and analyze console logs to see that empty custom settings are used for maven
 
```
7:15:39  [DEBUG] MavenSettings: dhreben-maven; name: ; id: 
[Pipeline] echo
17:15:39  [INFO] mavenBuild->call
[Pipeline] echo
17:15:39  [DEBUG] mavenSettingsConfig: 
```

9.Tap Manage Jenkins -> Managed files -> Add a new Config -> Maven settings.xml
 -  Copy ID
 -  Submit -> paste customized maven settings -> Submit

10.Open Run RegisterMavenSettings  ->  Build with Parameters
-  Enter your folder name (dhreben)
-  Paste maven ID

 11.Tap Build 

Actual result: RegisterMavenSettings doesn't work

```
Started by user admin
Resume disabled by user, switching to high-performance, low-durability mode.
Loading library Zebrunner-CE@#1.3
Attempting to resolve #1.3 from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
 > git ls-remote -h -- https://github.com/zebrunner/pipeline-ce.git # timeout=10
Could not find #1.3 in remote references. Pulling heads to local for deep search...
Creating git repository in /var/jenkins_home/caches/git-efd8370ace7bf69363d8c60b9c786a75
 > git init /var/jenkins_home/caches/git-efd8370ace7bf69363d8c60b9c786a75 # timeout=10
Setting origin to https://github.com/zebrunner/pipeline-ce.git
 > git config remote.origin.url https://github.com/zebrunner/pipeline-ce.git # timeout=10
Fetching origin...
Fetching upstream changes from origin
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
 > git config --get remote.origin.url # timeout=10
 > git fetch --tags --force --progress -- origin +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse #1.3^{commit} # timeout=10
ERROR: Could not resolve #1.3
hudson.plugins.git.GitException: Command "git rev-parse #1.3^{commit}" returned status code 128:
stdout: #1.3^{commit}

stderr: fatal: ambiguous argument '#1.3^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2380)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2376)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1923)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1935)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:1037)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:331)
	at jenkins.plugins.git.AbstractGitSCMSource$10.run(AbstractGitSCMSource.java:988)
	at jenkins.plugins.git.AbstractGitSCMSource$10.run(AbstractGitSCMSource.java:982)
	at jenkins.plugins.git.AbstractGitSCMSource.doRetrieve(AbstractGitSCMSource.java:374)
	at jenkins.plugins.git.AbstractGitSCMSource.doRetrieve(AbstractGitSCMSource.java:330)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:982)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:636)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.lambda$retrieve$0(SCMSourceRetriever.java:92)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrySCMOperation(SCMSourceRetriever.java:107)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:92)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:157)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:138)
	at org.jenkinsci.plugins.workflow.libs.LibraryDecorator$1.call(LibraryDecorator.java:125)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: No version #1.3 found for library Zebrunner-CE
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

```

**Comment by vdelendik** [comment]
@dhreben please retest one more time

**Comment by dhreben** [comment]
the same situation with RegisterMavenSettings

**Comment by vdelendik** [comment]
fixed. 1.3 jenkins-master was rebuilt. so make sure to remove existing image before testing

**Comment by dhreben** [comment]
Verified. Fixed.

<img width="858" alt="Screenshot 2020-12-03 at 20 40 55" src="https://user-images.githubusercontent.com/50950954/101066837-da1bd600-35a7-11eb-88e9-fd7b9a4b74e9.png">
