### ISSUE TITLE
try to share dump reports if any in maven job console log

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#99]
we publish dump as html report. it seems like new jenkins doesn't allow to do it because file is txt.
Also if possible we have to register dump report content as test run comment

**Comment by vdelendik** [comment]
done. to test you have to follow such scenario:
1. setup zebrunner from develop branch
2. update global jenkins var ZEBRUNNER_VERSION=develop
3. register organization (put into the reporting token mistake to emulate not valid token)
4. register carina-demo using "zbr-log4j2" branch
5. run any job
-> job status should be red (failed)
-> inside console log you should see similar error message:
```
[INFO] # Created at 2021-01-14T11:20:11.058
java.lang.ExceptionInInitializerError
	at com.zebrunner.agent.core.registrar.LogsBuffer.create(LogsBuffer.java:12)
	at com.zebrunner.agent.core.logging.log4j.ReportingAppender.getBuffer(ReportingAppender.java:29)
	at com.zebrunner.agent.core.logging.log4j.ReportingAppender.append(ReportingAppender.java:22)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.info(Category.java:666)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.<clinit>(CarinaListener.java:135)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.nordstrom.automation.testng.ListenerChain.attachListener(ListenerChain.java:676)
	at com.nordstrom.automation.testng.ListenerChain.processLinkedListeners(ListenerChain.java:639)
	at com.nordstrom.automation.testng.ListenerChain.attachListeners(ListenerChain.java:610)
	at com.nordstrom.automation.testng.ListenerChain.transform(ListenerChain.java:83)
	at org.testng.internal.annotations.JDK15AnnotationFinder.transform(JDK15AnnotationFinder.java:168)
	at org.testng.internal.annotations.JDK15AnnotationFinder.lambda$findAnnotation$0(JDK15AnnotationFinder.java:236)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:234)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:109)
	at org.testng.internal.TestNGClassFinder.isTestNGClass(TestNGClassFinder.java:280)
	at org.testng.internal.TestNGClassFinder.isNotTestNGClass(TestNGClassFinder.java:265)
	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:98)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:71)
	at org.testng.TestRunner.initMethods(TestRunner.java:437)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:180)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: ServerException(message=Not able to refresh access token.
Response status code: 401.
Raw response body: 
{"code":"IAM-3102","message":"Refresh token cannot be used, since user password has been changed."})
	at com.zebrunner.agent.core.registrar.ZebrunnerApiClient.authenticateClient(ZebrunnerApiClient.java:78)
	at com.zebrunner.agent.core.registrar.ZebrunnerApiClient.<init>(ZebrunnerApiClient.java:53)
	at com.zebrunner.agent.core.registrar.ZebrunnerApiClient.getInstance(ZebrunnerApiClient.java:63)
	at com.zebrunner.agent.core.registrar.FlushingLogsBuffer.<clinit>(FlushingLogsBuffer.java:27)
	... 46 more
```

**Comment by okamara** [comment]
Verified. Fixed.
